settings/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 
from django.contrib.auth import views as auth_views
from main.views import (
    HomeView,
    RegistrationView,
    LoginView,
    LogoutView,
    ProfileView,
    
    VagasView,
    DetalhesVagaView,
    
    DadosPessoaisView, 
    FormacaoView, 
    DeleteFormacaoView,
    ExperienciaView, 
    DeleteExperienciaView,
    IdiomaView, 
    DeleteIdiomaView,
    TecnologiaView, 
    DeleteTecnologiaView,
    DadosComplementaresView,
    
    QuestionarioView,
    ArquivosView,
    ContatoView,
    AjudaView,
    TermoView,
    CookiesView,
    
    ResumeCurriculoView,
    ResumeVagasView,
    DeleteVagaView,
    )

from adm.views import (
    AdministracaoView,  
    CandidatoView,  
    
    CadReqAdmin,
    CadFaseAdmin,
    CadVagaAdmin,
    CadCargoAdmin,
    CadSetorAdmin,
    CadFaseUsuarioAdmin,
    
    RequisicaoAdmin,
    AprovaAdmin,
    CurriculoAdmin,
    ContasAdmin,
    CurriculosAdmin,
    DocumentosAdmin,
    QuestionariosAdmin,
    FasesAdmin,
    
    DelVagaAdmin,
    DelCargoAdmin,
    DelSetorAdmin,
    DelFaseAdmin,
    DelFaseUsuarioAdmin,
    
    UpdateReqAdmin,
    UpdateVagaAdmin,
    UpdateStatVagaAdmin,
    UpdateVencVagaAdmin,
    UpdateVagaUsuarioAdmin,
    UpdateQuestAdmin,
    UpdateFaseUsuario,    
    
    DuplicateVagaAdmin,
    )

urlpatterns = [    
    ###################################################################################################################################
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
	re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
	re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

    path('admin/', admin.site.urls),
    path('', HomeView, name="home"),
    path('registrar/', RegistrationView, name="registrar"),
    path('entrar/', LoginView, name="entrar"),
    path('sair/', LogoutView, name="sair"),
    
    path('perfil/', ProfileView, name="perfil"),
    
    path('perfil/meu_curriculo', ResumeCurriculoView, name="meu_curriculo"),
    path('perfil/minhas_vagas', ResumeVagasView, name="minhas_vagas"),
    path('perfil/minhas_vagas/deletar_vaga/<nr_item>', DeleteVagaView, name="deletar_vaga"),
    
    path('perfil/enviar/arquivos', ArquivosView, name="arquivos"),
    path('perfil/ajuda', AjudaView, name="ajuda"),
    path('contato', ContatoView, name="contato"),
    path('termo', TermoView, name="termo"),
    path('politica_de_cookies', CookiesView, name="politica_de_cookies"),
    
    path('vagas/', VagasView, name="vagas"),
    path('vagas/detalhes_vaga/<nr_item>', DetalhesVagaView, name="detalhes_vaga"),
    
    path('perfil/cadastrar/dados_pessoais', DadosPessoaisView, name="dados_pessoais"),
    path('perfil/cadastrar/formacoes_academicas', FormacaoView, name="formacoes_academicas"),
    path('perfil/excluir/formacao/<nr_item>', DeleteFormacaoView, name="deletar_formacao"),
    path('perfil/cadastrar/experiencias_profissionais', ExperienciaView, name="experiencias_profissionais"),
    path('perfil/excluir/experiencia/<nr_item>', DeleteExperienciaView, name="deletar_experiencia"),
    path('perfil/cadastrar/idiomas', IdiomaView, name="idiomas"),
    path('perfil/excluir/idioma/<nr_item>', DeleteIdiomaView, name="deletar_idioma"),
    path('perfil/cadastrar/tecnologias', TecnologiaView, name="tecnologias"),
    path('perfil/excluir/tecnologia/<nr_item>', DeleteTecnologiaView, name="deletar_tecnologia"),
    path('perfil/cadastrar/dados_complementares', DadosComplementaresView, name="dados_complementares"),
    path('perfil/cadastrar/questionario', QuestionarioView, name="questionario"),
    
    
    path('recuperar_senha/', auth_views.PasswordResetView.as_view(), name='password_reset'),    
    path('recuperar_senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('perfil/alterar_senha', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    ###################################################################################################################################
    
    #URL INICIAL
    path('administracao', AdministracaoView, name="administracao"),
    path('administracao/candidatos', CandidatoView, name="candidatos"),

    #URLS DE CADASTRO
    path('administracao/cadastrar/requisicao', CadReqAdmin, name="cadastrar_requisicao"),
    path('administracao/cadastrar/vagas', CadVagaAdmin, name="cadastrar_vagas"),
    path('administracao/cadastrar/cargos', CadCargoAdmin, name="cadastrar_cargos"),
    path('administracao/cadastrar/setores', CadSetorAdmin, name="cadastrar_setores"),
    path('administracao/cadastrar/fases', CadFaseAdmin, name="cadastrar_fases"),
    path('administracao/cadastrar/fases_usuario/<nr_item>', CadFaseUsuarioAdmin, name="cadastrar_faseusuaurio"),
       
    #URLS DE VISUALIZAÇÃO
    path('administracao/visualizar/requisicoes', RequisicaoAdmin, name="requisicoes"),
    path('administracao/visualizar/aprovacao/requisicoes', AprovaAdmin, name="aprovacoes"),
    path('administracao/visualizar/curriculo/pdf/<nr_item>', CurriculoAdmin, name="curriculo"),
    path('administracao/visualizar/contas', ContasAdmin, name="contas"),
    path('administracao/visualizar/curriculos', CurriculosAdmin, name="curriculos"),
    path('administracao/visualizar/documentos', DocumentosAdmin, name="documentos"),
    path('administracao/visualizar/questionarios', QuestionariosAdmin, name="questionarios"),
    path('administracao/visualizar/fases', FasesAdmin, name="fases"),
    
    #URLS DE EXCLUSÃO
    path('administracao/deletar/vaga/<nr_item>', DelVagaAdmin, name="deletar_vaga"),
    path('administracao/deletar/cargo/<nr_item>', DelCargoAdmin, name="deletar_cargo"),
    path('administracao/deletar/setor/<nr_item>', DelSetorAdmin, name="deletar_setor"),
    path('administracao/deletar/fase/<nr_item>', DelFaseAdmin, name="deletar_fase"),
    path('administracao/deletar/fase_usuario/<nr_item>', DelFaseUsuarioAdmin, name="deletar_fase_usuario"),
    
    #URLS DE ALTERAÇÃO    
    path('administracao/update/requisicao/<nr_item>', UpdateReqAdmin, name="alterar_requisicao"),
    path('administracao/update/vaga/<nr_item>', UpdateVagaAdmin, name="alterar_vaga"),
    path('administracao/update/vaga/status/<nr_item>', UpdateStatVagaAdmin, name="update_vaga"),
    path('administracao/update/vaga/vencimento/<nr_item>', UpdateVencVagaAdmin, name="vencimento_vaga"),
    path('administracao/update/vagausuario/<nr_item>', UpdateVagaUsuarioAdmin, name="alterar_vagausuario"),
    path('administracao/update/questionario/<nr_item>', UpdateQuestAdmin, name="alterar_questionario"),
    path('administracao/update/faseusuario/<nr_item>', UpdateFaseUsuario, name="alterar_faseusuario"),
    
    #URLS DE DUPLICAÇÃO
    path('administracao/duplicar/vaga/<nr_item>', DuplicateVagaAdmin, name="duplicate_vaga"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adm/forms.py
from django import forms
from main.models import (
    ESCOLARIDADE, EXTINT, CONTRATOS, 
    Filial, Setores, Cargos, Contas, Cargos, Setores, Vagas, 
    Fase, FaseUsuario, Requisicao
)

class CadReqForm(forms.ModelForm):
    try:
        Requisicao.objects.all()
        cod = Requisicao.objects.all().last().codigo
    except:
        cod = 0

    codigo      = forms.IntegerField(widget=forms.NumberInput(attrs={'value': cod + 1}))
    gestor      = forms.ModelChoiceField(queryset=Contas.objects.all().filter(is_gestor=True))
    filial      = forms.ModelChoiceField(queryset=Filial.objects.all().order_by('cidade'))
    setor       = forms.ModelChoiceField(queryset=Setores.objects.all().order_by('nome_setor'))
    cargo       = forms.ModelChoiceField(queryset=Cargos.objects.all().order_by('nome_cargo'))
    tipo        = forms.ChoiceField(choices=EXTINT)
    tipo_vaga   = forms.ChoiceField(choices=CONTRATOS)
    ensino      = forms.ChoiceField(choices=ESCOLARIDADE)

    class Meta:
        model = Requisicao
        fields = '__all__'
        read_only_fields = ['status_a', 'usuario_a', 'data_a']
        exclude = ['is_active', 'status_b', 'usuario_b', 'data_b', 'status_c', 'usuario_c', 'data_c', 'status_d', 'usuario_d', 'data_d']


class CadVagaForm(forms.ModelForm):
    try:
        Vagas.objects.all()
        cod = Vagas.objects.all().last().codigo_vaga
    except:
        cod = 0

    data_validade   = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    codigo_vaga     = forms.IntegerField(widget=forms.NumberInput(attrs={'value': cod + 1}))
    quantidade      = forms.IntegerField(widget=forms.NumberInput(attrs={'value': 1}))
    status_vaga     = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': True}))
    setor           = forms.ModelChoiceField(queryset=Setores.objects.all().order_by('nome_setor'))
    cargo           = forms.ModelChoiceField(queryset=Cargos.objects.all().order_by('nome_cargo'))
    regiao          = forms.ModelChoiceField(queryset=Filial.objects.all().order_by('cidade'))

    class Meta:
        model = Vagas
        fields = '__all__'


class CadSetorForm(forms.ModelForm):
    class Meta:
        model = Setores
        fields = '__all__'
        
        
class CadCargoForm(forms.ModelForm):
    class Meta:
        model = Cargos
        fields = '__all__'
        

class CadFaseForm(forms.ModelForm):
    class Meta:
        model = Fase
        fields = '__all__'
        

class CadUserFaseForm(forms.ModelForm):       
    class Meta:
        model = FaseUsuario
        fields = '__all__'

adm/templates/update/update_fase_usuario.html
{% extends 'index.html' %}
{% load static %}
{% load chartkick %}
{% block content %}

<link rel="stylesheet" href="{% static 'adm/assets/css/candidatos.css' %}?{% now 'U' %}" type="text/css" />

<div id="wrapper">
	<div id="main">
		<div class="inner">

			{% include 'mensagem.html' %}

			<!-- Inicio Header -->
			<header id="header">
				<span class="label"><strong>Administração</strong> >> Fase - Usuário >> Editar</span>
				<ul class="icons">
					<li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i class="fas fa-address-card"></i></strong></li>
				</ul>
			</header>
			<!-- Fim Header -->

			<!-- Inicio Contas -->
			<section>
				<form method="POST">
					{% csrf_token %}
					{% for i in fase %}
						<header class="major">
							<h3>{{i.fase}} - {{ i.usuario }}</h3>
						</header>

						<div id="div_obs" style="display: none" value="{{ i.observacao }}">{{ i.observacao|safe }}</div>

						{{ form.observacao }}

						<script>
							window.onload = function () {
								var t = document.getElementById("div_obs").getAttribute('value');
								CKEDITOR.instances.id_observacao.setData(t);
							};
						</script>
						<br>
					{% endfor %}	
					<button class="btn mt-5" type="submit">Salvar</button>
				</form>
			</section>
			<!-- Fim Contas -->

		</div>
	</div>

	{% include 'menu.html' %}
	{% include 'adm/assets/js/main.html' %}
	
</div>
{% endblock content %}

adm/templates/update/update_requisicao.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div id="wrapper">
    <div id="main">
        <div class="inner">

            {% include 'mensagem.html' %}

            <!-- Inicio Header -->
            <header id="header">
                <span class="label"><strong>Administração</strong> >> Editar >> Requisicao</span>
                <ul class="icons">
                    <li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i class="fas fa-address-card"></i></strong></li>
                </ul>
            </header>
            <!-- Fim Header -->

            <script src="https://cdn.ckeditor.com/4.16.1/standard-all/ckeditor.js"></script>
            <section id="banner">
                <div class="content">
                    <form method="post">
                        {% csrf_token %}
                        {% for i in requisicao %}
                            <div class="row" style="margin-bottom: 1rem">
                                <div class="col-2">
                                    <label>Código</label>
                                    <input type="number" name="codigo" value="{{i.codigo}}" required="" id="id_codigo">
                                </div>
                                <div class="col-4">
                                    <label>Contratação</label>
                                    <select name="tipo_vaga" required="" id="id_tipo_vaga">
                                        <option value="{{i.tipo_vaga}}" hidden selected="">{{i.tipo_vaga}}</option>
                                        {% for f in contratos %}
                                            <option value="{{f}}">{{f}}</option>   
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-4">
                                    <label>Nível de Ensino</label>
                                    <select name="ensino" required="" id="id_ensino">
                                        <option value="{{i.ensino}}" hidden selected="">{{i.ensino}}</option>
                                        {% for f in escolaridade %}
                                            <option value="{{f}}">{{f}}</option>   
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 1rem">
                                <div class="col-4">
                                    <label>Regiao</label>
                                    <select name="filial" required="" id="id_filial">
                                        <option value="{{i.filial.id}}" hidden selected="">{{i.filial}}</option>
                                        {% for f in filiais %}
                                            <option value="{{f.id}}">{{f.cidade}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-4">
                                    <label>Setor</label>
                                    <select name="setor" required="" id="id_setor">
                                        <option value="{{i.setor.id}}" hidden selected="">{{i.setor}}</option>
                                        {% for f in setores %}
                                            <option value="{{f.id}}">{{f}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-4">
                                    <label>Cargo</label>
                                    <select name="cargo" required="" id="id_cargo">
                                        <option value="{{i.cargo.id}}" hidden selected="">{{i.cargo}}</option>
                                        {% for f in cargos %}
                                            <option value="{{f.id}}">{{f}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <br>
                            <div class="row" style="margin-bottom: 1rem">
                                <div class="col-4">
                                    <label>Salario</label>
                                    <input type="number" name="salario" value="{{i.salario}}" required="" id="id_salario">
                                </div>
                                <div class="col-4">
                                    <label>Gestor</label>
                                    <select name="gestor" required="" id="id_gestor">
                                        <option value="{{i.gestor.id}}" hidden selected="">{{i.gestor.username}}</option>
                                        {% for f in gestores %}
                                            <option value="{{f.id}}">{{f.username}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-4">
                                    <label>Tipo de requisição</label>
                                    <select name="tipo" required="" id="id_tipo">
                                        <option value="{{i.tipo}}" hidden selected="">{{i.tipo}}</option>
                                        {% for f in exitint %}
                                            <option value="{{f}}">{{f}}</option>   
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <br>

                            <div style="margin-bottom: 1rem">
                                <label>Requisitos</label>
                                <textarea cols="40" id="id_requisitos" maxlength="1024" name="requisitos" rows="10">{{i.requisitos|safe}}</textarea>
                            </div>

                            <div style="margin-bottom: 1rem">
                                <label>Atividades</label>
                                <textarea cols="40" id="id_atividades" maxlength="1024" name="atividades" rows="10">{{i.atividades|safe}}</textarea>
                            </div>

                            <div style="margin-bottom: 1rem">
                                <label>Habilidades</label>
                                <textarea cols="40" id="id_habilidades" maxlength="1024" name="habilidades" rows="10">{{i.habilidades|safe}}</textarea>
                            </div>

                            <div style="margin-bottom: 1rem">
                                <label>Ferramentas</label>
                                <textarea cols="40" id="id_ferramentas" maxlength="1024" name="ferramentas" rows="10">{{i.ferramentas|safe}}</textarea>
                            </div>

                            <div style="margin-bottom: 1rem">
                                <label>Recrutamento</label>
                                <textarea cols="40" id="id_recrutamento" maxlength="1024" name="recrutamento" rows="10">{{i.recrutamento|safe}}</textarea>
                            </div>

                            <div style="margin-bottom: 1rem">
                                <label>Informações</label>
                                <textarea cols="40" id="id_informacoes" maxlength="1024" name="informacoes" rows="10">{{i.informacoes|safe}}</textarea>
                            </div>

                            {% if i.usuario_a == request.user %}
                                <button name="alterar_requisicao" value={{i.id}} type="submit">Salvar</button>
                                <button name="excluir_requisicao" value={{i.id}} style="box-shadow: inset 0 0 0 2px red; color: red !important;" type="submit">Excluir</button>
                            {% else %}
                                <script type="text/javascript">
                                    document.getElementById('id_codigo').setAttribute('readonly', true);
                                    document.getElementById('id_ensino').setAttribute('readonly', true);
                                    document.getElementById('id_tipo_vaga').setAttribute('readonly', true);
                                    document.getElementById('id_filial').setAttribute('readonly', true);
                                    document.getElementById('id_setor').setAttribute('readonly', true);
                                    document.getElementById('id_cargo').setAttribute('readonly', true);
                                    document.getElementById('id_salario').setAttribute('readonly', true);
                                    document.getElementById('id_gestor').setAttribute('readonly', true);
                                    document.getElementById('id_tipo').setAttribute('readonly', true);
                                    document.getElementById('id_requisitos').setAttribute('readonly', true);
                                    document.getElementById('id_atividades').setAttribute('readonly', true);
                                    document.getElementById('id_habilidades').setAttribute('readonly', true);
                                    document.getElementById('id_ferramentas').setAttribute('readonly', true);
                                    document.getElementById('id_recrutamento').setAttribute('readonly', true);
                                    document.getElementById('id_informacoes').setAttribute('readonly', true);
                                </script>
                                <style>
                                    select[readonly] {
                                        pointer-events:none;
                                    }
                                }</style>
                            {% endif %}
                        {% endfor %}
                    </form>
                </div>
            </section>

            <style>
                [type="number"] {
                    border-radius: 5px;
                    height: 2.75em;
                    border: solid 1px rgba(210, 215, 217, 0.75);
                }

                [type="date"] {
                    background: #fff url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png) 97% 50% no-repeat;
                    height: 2.75em;
                    border: solid 1px rgba(210, 215, 217, 0.75);
                    border-radius: 5px;
                }

                [type="date"]::-webkit-inner-spin-button {
                    display: none;
                }

                [type="date"]::-webkit-calendar-picker-indicator {
                    opacity: 0;
                }
            </style>
        </div>
    </div>

    {% include 'menu.html' %}

    <script>
        CKEDITOR.replace('id_requisitos');
        CKEDITOR.replace('id_atividades');
        CKEDITOR.replace('id_habilidades');
        CKEDITOR.replace('id_ferramentas');
        CKEDITOR.replace('id_recrutamento');
        CKEDITOR.replace('id_informacoes');
    </script>

</div>

{% endblock content %}

adm/templates/update/update_vaga.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div id="wrapper">
    <div id="main">
        <div class="inner">

            {% include 'mensagem.html' %}

            <!-- Inicio Header -->
            <header id="header">
                <span class="label"><strong>Administração</strong> >> Editar >> Vaga</span>
                <ul class="icons">
                    <li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i class="fas fa-address-card"></i></strong></li>
                </ul>
            </header>
            <!-- Fim Header -->

            <!-- Inicio Cadastro -->
            <script src="https://cdn.ckeditor.com/4.16.1/standard-all/ckeditor.js"></script>
            <section id="banner">
                <div class="content">
                    <form method="post">
                        {% csrf_token %}
                        {% for i in vaga %}
                        <div class="row">
                            <div class="col">
                                <label>Vaga ativa
                                    {% if i.status_vaga %}
                                        <input style="margin-left: 1rem" type="checkbox" checked name="status_vaga" id="id_status_vaga">
                                    {% else %}
                                        <input style="margin-left: 1rem" type="checkbox" name="status_vaga" id="id_status_vaga">
                                    {% endif %}
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>Código da vaga</label>
                                <input type="number" name="codigo_vaga" value="{{i.codigo_vaga}}" required="" id="id_codigo_vaga">
                            </div>
                            <div class="col">
                                <label>Qtd de vagas</label>
                                <input type="number" name="quantidade" value="{{i.quantidade}}" required="" id="id_quantidade">
                            </div>
                            <div class="col">
                                <label>Validade</label>
                                <input type="date" name="data_validade" value="{{i.data_validade|date:'Y-m-d' }}" required="" id="id_data_validade">
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-4">
                                <label>Prioridade da vaga</label>
                                <select name="prioridade" required="" id="id_prioridade">
                                    <option value="{{i.prioridade}}" hidden selected="">{{i.prioridade}}</option>
                                    {% for i in prioridades %}
                                        <option value="{{i}}">{{i}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-4">
                                <label>Setor</label>
                                <select name="setor" required="" id="id_setor">
                                    <option value="{{i.setor.id}}" hidden selected="">{{i.setor}}</option>
                                    {% for i in setores %}
                                        <option value="{{i.id}}">{{i}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-4">
                                <label>Cargo</label>
                                <select name="cargo" required="" id="id_cargo">
                                    <option value="{{i.cargo.id}}" hidden selected="">{{i.cargo}}</option>
                                    {% for i in cargos %}
                                        <option value="{{i.id}}">{{i}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-3">
                                <label>Jornada de trabalho</label>
                                <input type="text" name="jornada" value="{{i.jornada}}" maxlength="32" required="" id="id_jornada">
                            </div>
                            <div class="col-3">
                                <label>Encolaridade</label>
                                <select name="ensino" required="" id="id_ensino">
                                    <option value="{{i.ensino}}" hidden selected="">{{i.ensino}}</option>
                                    {% for i in escolaridade %}
                                        <option value="{{i}}">{{i}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-3">
                                <label>Tipo de contrato</label>
                                <select name="contratacao" required="" id="id_contratacao">
                                    <option value="{{i.contratacao}}" hidden selected="">{{i.contratacao}}</option>
                                    {% for i in contratos %}
                                        <option value="{{i}}">{{i}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-3">
                                <label>Região</label>
                                <select name="regiao" required="" id="id_regiao">
                                    <option value="{{i.regiao.id}}" hidden selected="">{{i.regiao}}</option>
                                    {% for i in filiais %}
                                        <option value="{{i.id}}">{{i.cidade}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <br>

                        <label>Atividades à serem realizadas</label>
                        <textarea cols="40" id="id_atividades" maxlength="1024" name="atividades" rows="10">{{i.atividades|safe}}</textarea>
                        <br>

                        <label>Qualificação requerida</label>
                        <textarea cols="40" id="id_qualificacao" maxlength="1024" name="qualificacao" rows="10">{{i.qualificacao|safe}}</textarea>
                        <br>

                        <label>Descrição da vaga</label>
                        <textarea cols="40" id="id_descricao" maxlength="1024" name="descricao" rows="10">{{i.descricao|safe}}</textarea>
                        <br>
                        <br>

                        <button type="submit">Salvar</button>
                        {% endfor %}
                    </form>
                </div>
            </section>
            <!-- Fim Cadastro -->

            <style>
                [type="number"] {
                    border-radius: 5px;
                    height: 2.75em;
                    border: solid 1px rgba(210, 215, 217, 0.75);
                }

                [type="date"] {
                    background: #fff url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png) 97% 50% no-repeat;
                    height: 2.75em;
                    border: solid 1px rgba(210, 215, 217, 0.75);
                    border-radius: 5px;
                }

                [type="date"]::-webkit-inner-spin-button {
                    display: none;
                }

                [type="date"]::-webkit-calendar-picker-indicator {
                    opacity: 0;
                }
            </style>
        </div>
    </div>

    {% include 'menu.html' %}

    <script>
        CKEDITOR.replace('id_atividades');
        CKEDITOR.replace('id_qualificacao');
        CKEDITOR.replace('id_descricao');
    </script>

</div>

{% endblock content %}