settings/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 
from django.contrib.auth import views as auth_views
from main.views import (
    HomeView,
    RegistrationView,
    LoginView,
    LogoutView,
    ProfileView,
    
    VagasView,
    DetalhesVagaView,
    
    DadosPessoaisView, 
    FormacaoView, 
    DeleteFormacaoView,
    ExperienciaView, 
    DeleteExperienciaView,
    IdiomaView, 
    DeleteIdiomaView,
    TecnologiaView, 
    DeleteTecnologiaView,
    DadosComplementaresView,
    
    QuestionarioView,
    ArquivosView,
    ContatoView,
    AjudaView,
    TermoView,
    CookiesView,
    
    ResumeCurriculoView,
    ResumeVagasView,
    DeleteVagaView,
    )

from adm.views import (
    AdministracaoView,  
    CandidatoView,  
    
    CadReqAdmin,
    CadFaseAdmin,
    CadVagaAdmin,
    CadCargoAdmin,
    CadSetorAdmin,
    CadFaseUsuarioAdmin,
    
    RequisicaoAdmin,
    AprovaAdmin,
    CurriculoAdmin,
    ContasAdmin,
    CurriculosAdmin,
    DocumentosAdmin,
    QuestionariosAdmin,
    FasesAdmin,
    
    DelVagaAdmin,
    DelCargoAdmin,
    DelSetorAdmin,
    DelFaseAdmin,
    DelFaseUsuarioAdmin,
    
    UpdateReqAdmin,
    UpdateVagaAdmin,
    UpdateStatVagaAdmin,
    UpdateVencVagaAdmin,
    UpdateVagaUsuarioAdmin,
    UpdateQuestAdmin,
    UpdateFaseUsuario,    
    
    DuplicateVagaAdmin,
    )

urlpatterns = [    
    ###################################################################################################################################
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
	re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
	re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

    path('admin/', admin.site.urls),
    path('', HomeView, name="home"),
    path('registrar/', RegistrationView, name="registrar"),
    path('entrar/', LoginView, name="entrar"),
    path('sair/', LogoutView, name="sair"),
    
    path('perfil/', ProfileView, name="perfil"),
    
    path('perfil/meu_curriculo', ResumeCurriculoView, name="meu_curriculo"),
    path('perfil/minhas_vagas', ResumeVagasView, name="minhas_vagas"),
    path('perfil/minhas_vagas/deletar_vaga/<nr_item>', DeleteVagaView, name="deletar_vaga"),
    
    path('perfil/enviar/arquivos', ArquivosView, name="arquivos"),
    path('perfil/ajuda', AjudaView, name="ajuda"),
    path('contato', ContatoView, name="contato"),
    path('termo', TermoView, name="termo"),
    path('politica_de_cookies', CookiesView, name="politica_de_cookies"),
    
    path('vagas/', VagasView, name="vagas"),
    path('vagas/detalhes_vaga/<nr_item>', DetalhesVagaView, name="detalhes_vaga"),
    
    path('perfil/cadastrar/dados_pessoais', DadosPessoaisView, name="dados_pessoais"),
    path('perfil/cadastrar/formacoes_academicas', FormacaoView, name="formacoes_academicas"),
    path('perfil/excluir/formacao/<nr_item>', DeleteFormacaoView, name="deletar_formacao"),
    path('perfil/cadastrar/experiencias_profissionais', ExperienciaView, name="experiencias_profissionais"),
    path('perfil/excluir/experiencia/<nr_item>', DeleteExperienciaView, name="deletar_experiencia"),
    path('perfil/cadastrar/idiomas', IdiomaView, name="idiomas"),
    path('perfil/excluir/idioma/<nr_item>', DeleteIdiomaView, name="deletar_idioma"),
    path('perfil/cadastrar/tecnologias', TecnologiaView, name="tecnologias"),
    path('perfil/excluir/tecnologia/<nr_item>', DeleteTecnologiaView, name="deletar_tecnologia"),
    path('perfil/cadastrar/dados_complementares', DadosComplementaresView, name="dados_complementares"),
    path('perfil/cadastrar/questionario', QuestionarioView, name="questionario"),
    
    
    path('recuperar_senha/', auth_views.PasswordResetView.as_view(), name='password_reset'),    
    path('recuperar_senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('perfil/alterar_senha', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    ###################################################################################################################################
    
    #URL INICIAL
    path('administracao', AdministracaoView, name="administracao"),
    path('administracao/candidatos', CandidatoView, name="candidatos"),

    #URLS DE CADASTRO
    path('administracao/cadastrar/requisicao', CadReqAdmin, name="cadastrar_requisicao"),
    path('administracao/cadastrar/vagas', CadVagaAdmin, name="cadastrar_vagas"),
    path('administracao/cadastrar/cargos', CadCargoAdmin, name="cadastrar_cargos"),
    path('administracao/cadastrar/setores', CadSetorAdmin, name="cadastrar_setores"),
    path('administracao/cadastrar/fases', CadFaseAdmin, name="cadastrar_fases"),
    path('administracao/cadastrar/fases_usuario/<nr_item>', CadFaseUsuarioAdmin, name="cadastrar_faseusuaurio"),
       
    #URLS DE VISUALIZAÇÃO
    path('administracao/visualizar/requisicoes', RequisicaoAdmin, name="requisicoes"),
    path('administracao/visualizar/aprovacao/requisicoes', AprovaAdmin, name="aprovacoes"),
    path('administracao/visualizar/curriculo/pdf/<nr_item>', CurriculoAdmin, name="curriculo"),
    path('administracao/visualizar/contas', ContasAdmin, name="contas"),
    path('administracao/visualizar/curriculos', CurriculosAdmin, name="curriculos"),
    path('administracao/visualizar/documentos', DocumentosAdmin, name="documentos"),
    path('administracao/visualizar/questionarios', QuestionariosAdmin, name="questionarios"),
    path('administracao/visualizar/fases', FasesAdmin, name="fases"),
    
    #URLS DE EXCLUSÃO
    path('administracao/deletar/vaga/<nr_item>', DelVagaAdmin, name="deletar_vaga"),
    path('administracao/deletar/cargo/<nr_item>', DelCargoAdmin, name="deletar_cargo"),
    path('administracao/deletar/setor/<nr_item>', DelSetorAdmin, name="deletar_setor"),
    path('administracao/deletar/fase/<nr_item>', DelFaseAdmin, name="deletar_fase"),
    path('administracao/deletar/fase_usuario/<nr_item>', DelFaseUsuarioAdmin, name="deletar_fase_usuario"),
    
    #URLS DE ALTERAÇÃO    
    path('administracao/update/requisicao/<nr_item>', UpdateReqAdmin, name="alterar_requisicao"),
    path('administracao/update/vaga/<nr_item>', UpdateVagaAdmin, name="alterar_vaga"),
    path('administracao/update/vaga/status/<nr_item>', UpdateStatVagaAdmin, name="update_vaga"),
    path('administracao/update/vaga/vencimento/<nr_item>', UpdateVencVagaAdmin, name="vencimento_vaga"),
    path('administracao/update/vagausuario/<nr_item>', UpdateVagaUsuarioAdmin, name="alterar_vagausuario"),
    path('administracao/update/questionario/<nr_item>', UpdateQuestAdmin, name="alterar_questionario"),
    path('administracao/update/faseusuario/<nr_item>', UpdateFaseUsuario, name="alterar_faseusuario"),
    
    #URLS DE DUPLICAÇÃO
    path('administracao/duplicar/vaga/<nr_item>', DuplicateVagaAdmin, name="duplicate_vaga"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.forms import formset_factory
from main.models import (
    Contas, Setores, DadosPessoais, Formacao, Experiencia, Idioma, Tecnologia, Complementar, Vagas, VagasUsuarios,
    Questionario, Arquivos, ImagensPerfil, Termo, Paises, Estados, Cidades, Tecnologias, Idiomas, Niveis, 
    INSPECAO, CNH, DISTANCIA, SEXO, CIVIL
)

# Configuração do WIDGET de data
class DateInput(forms.DateInput):
    input_type = 'date'
    

# Form de Registrar Conta
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text='Adicione um email válido.')
    password1 = forms.CharField(help_text='Sua senha deve conter letras, números e caracteres especiais.')
    class Meta:
        model = Contas
        fields = ("email", "username", "password1", "password2")


# Form de Autenticação de Conta
class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Contas
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Login inválido!")


# Form de Update da Conta
class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Contas
        fields = ('email', 'username', )

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                contas = Contas.objects.exclude(pk=self.instance.pk).get(email=email)
            except Contas.DoesNotExist:
                return email
            raise forms.ValidationError('Este email já foi utilizado. Por favor escolha outro.')
    
    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                contas = Contas.objects.exclude(pk=self.instance.pk).get(username=username)
            except Contas.DoesNotExist:
                return username
            raise forms.ValidationError('Este nome já foi utilizado. Por favor escolha outro.')


# Form para Contatos Diretos
class ContatoForm(forms.Form):
    from_name = forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    from_telefone = forms.CharField()
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    

# Form Dados Pessoais
class DadosPessoaisForm(forms.ModelForm):  
    pais            = forms.ModelChoiceField(queryset=Paises.objects.all().order_by('name'))
    estado          = forms.ModelChoiceField(queryset=Estados.objects.filter(country=31).order_by('name'))
    cidade          = forms.ModelChoiceField(queryset=Cidades.objects.filter(country=31).order_by('name'))
    sexo            = forms.ChoiceField(required=True, choices=SEXO)
    estado_civil    = forms.ChoiceField(required=True, choices=CIVIL)

    class Meta:
        model = DadosPessoais
        fields = '__all__'
        exclude = ['usuario']
        widgets = {
            'data_nascimento': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DadosPessoaisForm, self).__init__(*args, **kwargs)
        
    def save(self, commit=True):
        obj = super(DadosPessoaisForm, self).save(commit=False)
        obj.usuario = self.user
        if commit:
            obj.save()
        return obj


# Form Formacao Academica
class FormacaoForm(forms.ModelForm):
    class Meta:
        model = Formacao
        fields = '__all__'
        exclude = ['usuario']      
FormacaoFormset = formset_factory(FormacaoForm, extra=1)


# Form Experiencias Profissionais
class ExperienciaForm(forms.ModelForm):
    cargo_exp = forms.CharField(widget=forms.Textarea(attrs={"rows":4}))
    atividades_exp = forms.CharField(widget=forms.Textarea(attrs={"rows":4}))
    atuacao  = forms.ModelChoiceField(queryset=Setores.objects.all().order_by('nome_setor'))
    class Meta:
        model = Experiencia
        fields = '__all__'
        exclude = ['usuario']
        widgets = {
            'data_entrada': DateInput(),
            'data_saida': DateInput(),
        }
ExperienciaFormset = formset_factory(ExperienciaForm, extra=1)
   
    
# Form Idiomas
class IdiomaForm(forms.ModelForm):
    idioma          = forms.ModelChoiceField(queryset=Idiomas.objects.all().order_by('idioma'))      
    nivel_idioma    = forms.ModelChoiceField(queryset=Niveis.objects.all().filter(grupo__in=[2,0]).order_by('id'))      
    class Meta:
        model = Idioma
        fields = '__all__'
        exclude = ['usuario']
IdiomaFormset = formset_factory(IdiomaForm, extra=1)


# Form Tecnologias
class TecnologiaForm(forms.ModelForm):
    sistema          = forms.ModelChoiceField(queryset=Tecnologias.objects.all().order_by('tecnologia'))      
    nivel_sistema    = forms.ModelChoiceField(queryset=Niveis.objects.all().filter(grupo__in=[2,1]).order_by('id')) 
    class Meta:
        model = Tecnologia
        fields = '__all__'
        exclude = ['usuario']
TecnologiaFormset = formset_factory(TecnologiaForm, extra=1)


# Form Dados Complementares
class DadosComplementaresForm(forms.ModelForm):  
    pretensao       = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'R$'}))
    interesse1      = forms.ModelChoiceField(queryset=Setores.objects.all().order_by('nome_setor'))
    interesse2      = forms.ModelChoiceField(queryset=Setores.objects.all().order_by('nome_setor'))
    inspecao        = forms.ChoiceField(required=True, choices=INSPECAO)
    cnh             = forms.ChoiceField(required=True, choices=CNH)
    distancia       = forms.ChoiceField(required=True, choices=DISTANCIA)

    class Meta:
        model = Complementar
        fields = '__all__'
        exclude = ['usuario'] 

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DadosComplementaresForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(DadosComplementaresForm, self).save(commit=False)
        obj.usuario = self.user
        if commit:
            obj.save()
        return obj
    
    
# Form Questionario
class QuestionarioForm(forms.ModelForm):
    class Meta:
        model = Questionario
        fields = '__all__'
        read_only_fields = ['pontuacao_questionario', 'usuario']


# Form Arquivos
class ArquivosForm(forms.ModelForm):
    documentos = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Arquivos
        fields = '__all__'
        exclude = ['usuario']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ArquivosForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(ArquivosForm, self).save(commit=False)
        obj.usuario = self.user
        if commit:
            obj.save()
        return obj


# Form Imagem Perfil
class ImagemForm(forms.ModelForm):
    class Meta:
        model = ImagensPerfil
        fields = '__all__'
        exclude = ['usuario']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ImagemForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(ImagemForm, self).save(commit=False)
        obj.usuario = self.user
        if commit:
            obj.save()
        return obj


# Form Vagas
class VagasForm(forms.ModelForm):
    class Meta:
        model = Vagas
        fields = '__all__'


# Form Cadastro Vagas
class VagasUsuariosForm(forms.ModelForm):
    class Meta:
        model = VagasUsuarios
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(VagasUsuariosForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(VagasUsuariosForm, self).save(commit=False)
        obj.usuario = self.user
        if commit:
            obj.save()
        return obj
VagasUsuariosFormset = formset_factory(VagasUsuariosForm)


# Form Termo de Uso
class TermoForm(forms.ModelForm):
    class Meta:
        model = Termo
        fields = '__all__'
        exclude = ['usuario']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TermoForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(TermoForm, self).save(commit=False)
        obj.usuario = self.user
        if commit:
            obj.save()
        return obj

main/templates/main/contato.html
<form method="post" action="" class="my-0">
    {% csrf_token %}
  
   <div class="modal-header d-flex justify-content-center">
      <h3 class="modal-title">Contate-nos</h3>
    </div>

    <div class="modal-body">
        <p>* Este email deve ser enviado apenas em caso de dúvidas e/ou dificuldades relacionadas ao cadastro de contas, curriculos e vagas em nosso 
        sistema.</p>
        <br>
        <div class="mb-2">
            <input class="form-control" type="text" name="from_name" required id="id_from_name" placeholder="Nome">
        </div>
        <div class="mb-2">
            <input class="form-control" type="text" name="from_email" required id="id_from_email" placeholder="Email">
        </div>
        <div class="mb-2">
            <input class="form-control" type="text" name="from_telefone" id="id_from_telefone" placeholder="Telefone">
        </div>
        <div class="mb-2">
            <input class="form-control" type="text" name="subject" required id="id_subject" placeholder="Assunto">
        </div>
        <div class="mb-3">
            <textarea class="form-control" type="text" name="message" required id="id_message" placeholder="Menssagem"></textarea>
        </div>
    </div>

    
    <div class="modal-footer">
        <a class="btn btn-secondary text-white d-flex align-items-center" style="height: 41.8px;" href="{{request.META.HTTP_REFERER|escape}}">Fechar</a>
        <button type="submit" class="btn btn-success text-white" id="submitButton">Enviar</button>
    </div>

</form>

{% include 'base/assets/java/java.html' %}

main/templates/main/cookies.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include '../mails/messages.html' %}

<section id="one" class="wrapper style2 mt-5">
    <div class="inner">
        <div class="grid-style my-0">
            <div class="col-md-12 col-12 d-flex justify-content-center align-self-center">
                <div class="box px-5 py-5">
                    <div>
                        <h2 style="color: green;">Política de Cookies</h2>

                        <p style="color: grey;"> Esta Política de Cookies explica o que são Cookies e como os usamos. Você deve
                            ler esta política para que você possa entender que tipo de cookies usamos, ou o
                            informações que coletamos usando Cookies e como essas informações são usadas.
                            Esta política de cookies foi criada com a ajuda do
                            <a href="https://www.termsfeed.com/cookies-policy-generator/" target="_blank">Cookies Policy
                                Generator</a>.
                        </p>

                        <p style="color: grey;"> Os cookies normalmente não contêm nenhuma informação que identifique pessoalmente um
                            usuário, mas as informações pessoais que armazenamos sobre você podem estar vinculadas ao
                            informações armazenadas e obtidas nos cookies. Para mais informações sobre
                            como usamos, armazenamos e mantemos seus dados pessoais seguros, consulte nossa Política de
                            Privacidade.
                        </p>

                        <p style="color: grey;"> Não armazenamos informações pessoais confidenciais, como endereços de correspondência,
                            senhas de contas, etc. nos cookies que usamos.
                        </p>

                        <h2 style="color: green;">Interepretação e Definições</h2>

                        <h4 style="color: #FFc30B">Interepretação</h4>

                        <p style="color: grey;"> As palavras cuja letra inicial é maiúscula têm significados definidos
                            sob as seguintes condições. As seguintes definições devem ter o mesmo
                            significado independentemente de eles aparecerem no singular ou no plural.
                        </p>

                        <h4 style="color: #FFc30B">Definições</h4>
                        <p style="color: grey;">Para os fins desta Política de Cookies:</p>
                        <ul>
                            <li style="color: grey;"><strong>Empresa</strong> (referida como "a Empresa", "Nós" ou "Nosso" nesta
                                Política de Cookies) refere-se à Trabalhe Conosco da Colorado Máquinas.
                            </li>

                            <li style="color: grey;"><strong>Cookies</strong> ignificam pequenos arquivos que são colocados em seu
                                computador, dispositivo móvel
                                ou qualquer outro dispositivo por um site, contendo detalhes de sua navegação
                                história naquele site entre seus muitos usos.
                            </li>

                            <li style="color: grey;"><strong>Website/Site</strong> refere-se a Trabalhe Conosco, acessível em
                                <a href="http://trabalheconosco.coloradomaquinas.com.br"
                                    rel="external nofollow noopener"
                                    target="_blank">http://trabalheconosco.coloradomaquinas.com.br </a>
                            </li>

                            <li style="color: grey;"><strong>Você</strong> significa o indivíduo que acessa ou usa o site, ou uma empresa, ou
                                qualquer pessoa jurídica em nome da qual esse indivíduo está acessando ou usando
                                o site, conforme aplicável.
                            </li>
                        </ul>

                        <h2 style="color: green;">O uso dos cookies</h2>

                        <h4 style="color: #FFc30B">Tipo de cookies que usamos</h4>

                        <p style="color: grey;">Os cookies podem ser cookies "persistentes" ou "de sessão". Cookies persistentes permanecem
                            ativados
                            seu computador pessoal ou dispositivo móvel quando você ficar offline, durante a sessão
                            Os cookies são excluídos assim que você fecha o navegador.
                        </p>

                        <p style="color: grey;">Usamos cookies de sessão e cookies persistentes para as finalidades definidas abaixo:</p>

                        <ul>
                            <li style="color: grey;">
                                <p style="color: grey;"><strong>Cookies necessários / essenciais</strong></p>
                                <p style="color: grey;">Tipo: Cookies de sessão</p>
                                <p style="color: grey;">Administrado por: Nós</p>
                                <p style="color: grey;">Objetivo: esses cookies são essenciais para fornecer serviços a você
                                    disponíveis através do site e para permitir que você use alguns de seus
                                    recursos. Eles ajudam a autenticar usuários e evitar o uso fraudulento de
                                    contas de usuário. Sem esses cookies, os serviços que você solicitou
                                    não podem ser fornecidos e nós apenas usamos esses cookies para fornecer a você
                                    esses serviços.</p>
                            </li>
                            <li style="color: grey;">
                                <p style="color: grey;"><strong>Cookies de funcionalidade</strong></p>
                                <p style="color: grey;">Tipo: Cookies Persistentes</p>
                                <p style="color: grey;">Administrado por: Nós</p>
                                <p style="color: grey;">Objetivo: Esses cookies nos permitem lembrar as escolhas que você faz quando usa
                                    o site, como lembrar seus detalhes de login ou idioma
                                    preferência. O objetivo desses cookies é fornecer a você mais
                                    experiência pessoal e para evitar que você tenha que inserir novamente suas
                                    preferências
                                    cada vez que você usa o site.</p>
                            </li>
                        </ul>
                        <h2 style="color: green;">Suas escolhas em relação aos cookies</h2>
                        <p style="color: grey;">Se preferir evitar o uso de cookies no site, primeiro você deve
                            desative o uso de cookies em seu navegador e, em seguida, exclua os cookies salvos
                            em seu navegador associado a este site. Você pode usar esta opção para
                            impedindo o uso de Cookies a qualquer momento.</p>
                        <p style="color: grey;">Se você não aceitar nossos cookies, poderá enfrentar alguns inconvenientes em
                            o uso do site e alguns recursos podem não funcionar corretamente.</p>
                        <p style="color: grey;">Se você gostaria de deletar Cookies ou instruir seu navegador para deletar ou
                            recusar Cookies, visite as páginas de ajuda do seu navegador.</p>
                        <ul>
                            <li style="color: grey;">
                                <p style="color: grey;">Para o navegador Chrome, visite esta página do Google: <a
                                        href="https://support.google.com/accounts/answer/32050"
                                        rel="external nofollow noopener"
                                        target="_blank">https://support.google.com/accounts/answer/32050</a></p>
                            </li>
                            <li style="color: grey;">
                                <p style="color: grey;">Para o navegador Internet Explorer, visite esta página em
                                    Microsoft: <a href="http://support.microsoft.com/kb/278835"
                                        rel="external nofollow noopener"
                                        target="_blank">http://support.microsoft.com/kb/278835</a></p>
                            </li>
                            <li style="color: grey;">
                                <p style="color: grey;">Para o navegador Firefox, visite esta página da Mozilla: <a
                                        href="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored"
                                        rel="external nofollow noopener"
                                        target="_blank">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</a>
                                </p>
                            </li>
                            <li style="color: grey;">
                                <p style="color: grey;">Para o navegador Safari, visite esta página da Apple: <a
                                        href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac"
                                        rel="external nofollow noopener"
                                        target="_blank">https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac</a>
                                </p>
                            </li>
                        </ul>
                        <p style="color: grey;">Para qualquer outro navegador, visite as páginas oficiais do seu navegador.</p>
                        <h2 style="color: green;">Mais informações sobre cookies</h2>
                        <p style="color: grey;">Você pode aprender mais sobre cookies aqui: <a href="https://www.termsfeed.com/blog/cookies/"
                                target="_blank">All About
                                Cookies by TermsFeed</a>.</p>
                        <h2 style="color: green;">Entre em contato conosco</h2>
                        <p style="color: grey;">Se você tiver alguma dúvida sobre esta Política de Cookies, pode entrar em contato conosco:
                        </p>
                        <ul>
                            <li style="color: grey;">Visitando nosso site e clicando em "Contato" (canto superior direito): <a
                                    href="http://trabalheconosco.coloradomaquinas.com.br"
                                    rel="external nofollow noopener"
                                    target="_blank">http://trabalheconosco.coloradomaquinas.com.br</a>
                            </li>
                        </ul>


                        <script async src='/cdn-cgi/bm/cv/669835187/api.js'></script>
                        <script type="text/javascript">(function () {
                                window['__CF$cv$params'] = {
                                    r: '621ecc7fedcd4d24',
                                    m: 'a080a17f3760c718fba3235a4092bf940a2a93f5-1613389696-1800-AbyL4qr5DNHcZPEB4uULu2j9/aIXitqwtOSF6piV3vT8RRl06SgzllyXDLfH2kVomLnxBF1eY6j/fiXHqid0fpV8kvLAuen8kDUDHczWdFjn/jJY2z0HkDg9MGLj6MOyzTGSaRdsT003WWD74E+31VJIPU/yI4AG0WrloKdPGV507iTMfHpf51AUH4nvvVSI/g==',
                                    s: [0xb02382d852, 0x1cd4f963f5],
                                }
                            })();
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}