settings/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 
from django.contrib.auth import views as auth_views
from main.views import (
    HomeView,
    RegistrationView,
    LoginView,
    LogoutView,
    ProfileView,
    
    VagasView,
    DetalhesVagaView,
    
    DadosPessoaisView, 
    FormacaoView, 
    DeleteFormacaoView,
    ExperienciaView, 
    DeleteExperienciaView,
    IdiomaView, 
    DeleteIdiomaView,
    TecnologiaView, 
    DeleteTecnologiaView,
    DadosComplementaresView,
    
    QuestionarioView,
    ArquivosView,
    ContatoView,
    AjudaView,
    TermoView,
    CookiesView,
    
    ResumeCurriculoView,
    ResumeVagasView,
    DeleteVagaView,
    )

from adm.views import (
    AdministracaoView,  
    CandidatoView,  
    
    CadReqAdmin,
    CadFaseAdmin,
    CadVagaAdmin,
    CadCargoAdmin,
    CadSetorAdmin,
    CadFaseUsuarioAdmin,
    
    RequisicaoAdmin,
    AprovaAdmin,
    CurriculoAdmin,
    ContasAdmin,
    CurriculosAdmin,
    DocumentosAdmin,
    QuestionariosAdmin,
    FasesAdmin,
    
    DelVagaAdmin,
    DelCargoAdmin,
    DelSetorAdmin,
    DelFaseAdmin,
    DelFaseUsuarioAdmin,
    
    UpdateReqAdmin,
    UpdateVagaAdmin,
    UpdateStatVagaAdmin,
    UpdateVencVagaAdmin,
    UpdateVagaUsuarioAdmin,
    UpdateQuestAdmin,
    UpdateFaseUsuario,    
    
    DuplicateVagaAdmin,
    )

urlpatterns = [    
    ###################################################################################################################################
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
	re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
	re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

    path('admin/', admin.site.urls),
    path('', HomeView, name="home"),
    path('registrar/', RegistrationView, name="registrar"),
    path('entrar/', LoginView, name="entrar"),
    path('sair/', LogoutView, name="sair"),
    
    path('perfil/', ProfileView, name="perfil"),
    
    path('perfil/meu_curriculo', ResumeCurriculoView, name="meu_curriculo"),
    path('perfil/minhas_vagas', ResumeVagasView, name="minhas_vagas"),
    path('perfil/minhas_vagas/deletar_vaga/<nr_item>', DeleteVagaView, name="deletar_vaga"),
    
    path('perfil/enviar/arquivos', ArquivosView, name="arquivos"),
    path('perfil/ajuda', AjudaView, name="ajuda"),
    path('contato', ContatoView, name="contato"),
    path('termo', TermoView, name="termo"),
    path('politica_de_cookies', CookiesView, name="politica_de_cookies"),
    
    path('vagas/', VagasView, name="vagas"),
    path('vagas/detalhes_vaga/<nr_item>', DetalhesVagaView, name="detalhes_vaga"),
    
    path('perfil/cadastrar/dados_pessoais', DadosPessoaisView, name="dados_pessoais"),
    path('perfil/cadastrar/formacoes_academicas', FormacaoView, name="formacoes_academicas"),
    path('perfil/excluir/formacao/<nr_item>', DeleteFormacaoView, name="deletar_formacao"),
    path('perfil/cadastrar/experiencias_profissionais', ExperienciaView, name="experiencias_profissionais"),
    path('perfil/excluir/experiencia/<nr_item>', DeleteExperienciaView, name="deletar_experiencia"),
    path('perfil/cadastrar/idiomas', IdiomaView, name="idiomas"),
    path('perfil/excluir/idioma/<nr_item>', DeleteIdiomaView, name="deletar_idioma"),
    path('perfil/cadastrar/tecnologias', TecnologiaView, name="tecnologias"),
    path('perfil/excluir/tecnologia/<nr_item>', DeleteTecnologiaView, name="deletar_tecnologia"),
    path('perfil/cadastrar/dados_complementares', DadosComplementaresView, name="dados_complementares"),
    path('perfil/cadastrar/questionario', QuestionarioView, name="questionario"),
    
    
    path('recuperar_senha/', auth_views.PasswordResetView.as_view(), name='password_reset'),    
    path('recuperar_senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('perfil/alterar_senha', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    ###################################################################################################################################
    
    #URL INICIAL
    path('administracao', AdministracaoView, name="administracao"),
    path('administracao/candidatos', CandidatoView, name="candidatos"),

    #URLS DE CADASTRO
    path('administracao/cadastrar/requisicao', CadReqAdmin, name="cadastrar_requisicao"),
    path('administracao/cadastrar/vagas', CadVagaAdmin, name="cadastrar_vagas"),
    path('administracao/cadastrar/cargos', CadCargoAdmin, name="cadastrar_cargos"),
    path('administracao/cadastrar/setores', CadSetorAdmin, name="cadastrar_setores"),
    path('administracao/cadastrar/fases', CadFaseAdmin, name="cadastrar_fases"),
    path('administracao/cadastrar/fases_usuario/<nr_item>', CadFaseUsuarioAdmin, name="cadastrar_faseusuaurio"),
       
    #URLS DE VISUALIZAÇÃO
    path('administracao/visualizar/requisicoes', RequisicaoAdmin, name="requisicoes"),
    path('administracao/visualizar/aprovacao/requisicoes', AprovaAdmin, name="aprovacoes"),
    path('administracao/visualizar/curriculo/pdf/<nr_item>', CurriculoAdmin, name="curriculo"),
    path('administracao/visualizar/contas', ContasAdmin, name="contas"),
    path('administracao/visualizar/curriculos', CurriculosAdmin, name="curriculos"),
    path('administracao/visualizar/documentos', DocumentosAdmin, name="documentos"),
    path('administracao/visualizar/questionarios', QuestionariosAdmin, name="questionarios"),
    path('administracao/visualizar/fases', FasesAdmin, name="fases"),
    
    #URLS DE EXCLUSÃO
    path('administracao/deletar/vaga/<nr_item>', DelVagaAdmin, name="deletar_vaga"),
    path('administracao/deletar/cargo/<nr_item>', DelCargoAdmin, name="deletar_cargo"),
    path('administracao/deletar/setor/<nr_item>', DelSetorAdmin, name="deletar_setor"),
    path('administracao/deletar/fase/<nr_item>', DelFaseAdmin, name="deletar_fase"),
    path('administracao/deletar/fase_usuario/<nr_item>', DelFaseUsuarioAdmin, name="deletar_fase_usuario"),
    
    #URLS DE ALTERAÇÃO    
    path('administracao/update/requisicao/<nr_item>', UpdateReqAdmin, name="alterar_requisicao"),
    path('administracao/update/vaga/<nr_item>', UpdateVagaAdmin, name="alterar_vaga"),
    path('administracao/update/vaga/status/<nr_item>', UpdateStatVagaAdmin, name="update_vaga"),
    path('administracao/update/vaga/vencimento/<nr_item>', UpdateVencVagaAdmin, name="vencimento_vaga"),
    path('administracao/update/vagausuario/<nr_item>', UpdateVagaUsuarioAdmin, name="alterar_vagausuario"),
    path('administracao/update/questionario/<nr_item>', UpdateQuestAdmin, name="alterar_questionario"),
    path('administracao/update/faseusuario/<nr_item>', UpdateFaseUsuario, name="alterar_faseusuario"),
    
    #URLS DE DUPLICAÇÃO
    path('administracao/duplicar/vaga/<nr_item>', DuplicateVagaAdmin, name="duplicate_vaga"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from ckeditor.fields import RichTextField
from django.db import models
import datetime, re

PRIORIDADE = [
    ("Baixa", "Baixa"),
    ("Média", "Média"), 
    ("Alta", "Alta"),
    ("Urgente", "Urgente")
]

CONTRATOS = [
    ("Aprendiz", "Aprendiz"),
    ("CLT", "CLT"),
    ("Estágio", "Estágio"),
    ("Temporario", "Temporario"),    
]

ESCOLARIDADE = [
    ("Ensino Médio", "Ensino Médio"),
    ("Ensino Técnico", "Ensino Técnico"),
    ("Ensino Superior", "Ensino Superior"),
    ("Pós Graduação", "Pós Graduação"),
    ("Mestrado", "Mestrado"),
    ("Doutorado", "Doutorado"),
]

CNH = [
    ("Não Possuo", "Não Possuo"),
    ("A", "A"),
    ("B", "B"),
    ("C", "C"),
    ("D", "D"),
    ("E", "E"),
]

SEXO = [
    ("Feminino", "Feminino"),
    ("Masculino", "Masculino"),
    ("Prefiro não declarar", "Prefiro não declarar"),
]

CIVIL = [
    ("Casado(a)", "Casado(a)"),
    ("Divorciado(a)", "Divorciado(a)"),
    ("Solteiro(a)", "Solteiro(a)"),
    ("Viúvo(a)", "Viúvo(a)"),
]

INSPECAO = [
    ("Facebook", "Facebook"),
    ("Indicação", "Indicação"),
    ("LinkedIn", "LinkedIn"),
    ("Site", "Site"),
    ("Outros", "Outros"),
]

FORMACAO = [
    ("Em Andamento", "Em Andamento"),
    ("Concluído", "Concluído"),
    ("Trancado", "Trancado"),
]

DISTANCIA = [
    ("50km ou menos", "50km ou menos"),
    ("50km - 100km", "50km - 100km"),
    ("100km - 150km", "100km - 150km"),
    ("150km - 200km", "150km - 200km"),
    ("200km ou mais", "200km ou mais"),
]

EXTINT = [
    ('Interno', 'Interno'),
    ('Externo', 'Externo'),
    ('Interno/Externo', 'Interno/Externo'),
]


def local_upload(instance, filename):
    file_path = 'profile/{usuario}/{data_envio}__imagem__{filename}'.format(
	    usuario=(instance.usuario.email), data_envio=datetime.date.today(), filename=re.sub('[^A-Za-z0-9.]+', '', filename))
    return file_path


def doc_upload(instance, filename):
	file_path = 'documentos/{usuario}/{data_envio}__documento__{filename}'.format(
		usuario=(instance.usuario.email), data_envio=datetime.date.today(), filename=re.sub('[^A-Za-z0-9.]+', '', filename))
	return file_path


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("O usuário deve conter um endereço de e-mail.")
        if not username:
            raise ValueError("O usuário deve conter um nome.")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_interno = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Contas(AbstractBaseUser, PermissionsMixin):
    email               = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username            = models.CharField(max_length=30, unique=True)
    data_inscricao      = models.DateTimeField(verbose_name='Data de Inscrição', auto_now_add=True)
    ultimo_login        = models.DateTimeField(verbose_name='Último Login', auto_now=True)
    is_admin            = models.BooleanField(default=False)
    is_active           = models.BooleanField(default=True)
    is_rh               = models.BooleanField(default=False)
    is_superuser        = models.BooleanField(default=False)
    is_interno          = models.BooleanField(default=False)
    is_gestor           = models.BooleanField(default=False)
    is_diretor          = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyAccountManager()
        
    def __str__(self):
        try:
            DadosPessoais.objects.get(usuario=self.id)
            q = DadosPessoais.objects.get(usuario=self.id)
            nome = q.nome_completo
            return nome
        except DadosPessoais.DoesNotExist:
            return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perm(self, app_label):
        return True
    
    class Meta:
        verbose_name = "Conta"
        verbose_name_plural = "Contas"


class Filial(models.Model):
    nome                       = models.CharField(max_length=32)           
    razao                      = models.CharField(max_length=191)  
    cnpj                       = models.CharField(max_length=32)  
    cidade                     = models.CharField(max_length=32)  
    endereco                   = models.CharField(max_length=191)  
    cep                        = models.CharField(max_length=32)  

    def __str__(self):
        return self.cidade
    
    class Meta:
        verbose_name = "Filial"
        verbose_name_plural = "Filiais"


class Cargos(models.Model):
    nome_cargo                 = models.CharField(max_length=64, verbose_name="Cargo")
    descricao_cargo            = models.CharField(max_length=64, null=True, blank=True, verbose_name="Descrição Cargo")

    def __str__(self):
        return self.nome_cargo
    
    class Meta:
        verbose_name = "Cargo"
        verbose_name_plural = "Cadastros de Cargos" 


class Setores(models.Model):
    nome_setor                 = models.CharField(max_length=64, verbose_name="Setor")
    descricao_setor            = models.CharField(max_length=64, null=True, blank=True, verbose_name="Descrição Setor")

    def __str__(self):
        return self.nome_setor
    
    class Meta:
        verbose_name = "Setor"
        verbose_name_plural = "Cadastros de Setores" 


class Niveis(models.Model):
    nivel                   = models.CharField(max_length=32)
    grupo                   = models.IntegerField()

    def __str__(self):
        return self.nivel
    
    class Meta:
        verbose_name = "Nível"
        verbose_name_plural = "Níveis" 


class Idiomas(models.Model):
    idioma                  = models.CharField(max_length=32)
    grupo                   = models.IntegerField()

    def __str__(self):
        return self.idioma
    
    class Meta:
        verbose_name = "Idioma"
        verbose_name_plural = "Idiomas" 


class Tecnologias(models.Model):
    tecnologia              = models.CharField(max_length=32)
    grupo                   = models.IntegerField()

    def __str__(self):
        return self.tecnologia
    
    class Meta:
        verbose_name = "Tecnologia"
        verbose_name_plural = "Tecnologias" 


class Paises(models.Model):
    name	                = models.CharField(max_length=255, verbose_name="Pais")
    iso3	                = models.CharField(max_length=255, verbose_name="ISO3")
    numeric_code	        = models.IntegerField(verbose_name="Codigo")
    iso2	                = models.CharField(max_length=255, verbose_name="ISO2")
    phonecode	            = models.CharField(max_length=191, verbose_name="Código Postal")
    capital	                = models.CharField(max_length=255, verbose_name="Capital")
    currency	            = models.CharField(max_length=255, verbose_name="Moeda")
    currency_name	        = models.CharField(max_length=255, verbose_name="Nome da Moeda")
    currency_symbol		    = models.CharField(max_length=255, verbose_name="Simbolo da Moeda")	
    tld	                    = models.CharField(max_length=255)
    native	                = models.CharField(max_length=255, null=True)
    region	                = models.CharField(max_length=255, verbose_name="Regiao")
    subregion	            = models.CharField(max_length=255, verbose_name="Subregiao")
    timezones               = models.TextField()
    translations            = models.TextField()
    latitude	            = models.DecimalField(max_digits=12, decimal_places=8, null=True, verbose_name="Latitude")
    longitude               = models.DecimalField(max_digits=12, decimal_places=8, null=True, verbose_name="Longitude")
    emoji                   = models.CharField(max_length=191, verbose_name="emoji")    # ascii
    emojiU                  = models.CharField(max_length=191, verbose_name="emojiU")
    created_at              = models.DateTimeField(verbose_name="Data Criacao")
    updated_at              = models.DateTimeField(verbose_name="Data Modificacao")
    flag                    = models.BooleanField(default=True, verbose_name="Flag")
    wikiDataId              = models.CharField(max_length=255, null=True, verbose_name="WikiDataId")

    def __str__(self):
        return str(self.name)
    
    class Meta:
        verbose_name = "País"
        verbose_name_plural = "Países"


class Estados(models.Model):
    name	                = models.CharField(max_length=255, verbose_name="Nome Cidade")
    country	                = models.ForeignKey(Paises, on_delete=models.CASCADE)
    country_code            = models.CharField(max_length=255, verbose_name="Cod Pais")
    fips_code               = models.CharField(max_length=255, null=True, verbose_name="FIPS")
    iso2                    = models.CharField(max_length=255, verbose_name="ISO2")
    typ                     = models.CharField(max_length=191, null=True, verbose_name="Type")
    latitude	            = models.DecimalField(max_digits=12, decimal_places=8, null=True, verbose_name="Latitude")
    longitude               = models.DecimalField(max_digits=12, decimal_places=8, null=True, verbose_name="Longitude")
    created_at              = models.DateTimeField(verbose_name="Data Criacao")
    updated_at              = models.DateTimeField(verbose_name="Data Modificacao")
    flag                    = models.BooleanField(default=True, verbose_name="Flag")

adm/templates/cadastrar/cadastrar_cargos.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div id="wrapper">
	<div id="main">
		<div class="inner">

			{% include 'mensagem.html' %}

			<!-- Inicio Header -->
			<header id="header">
				<span class="label"><strong>Administração</strong> >> Cadastrar >> Cargo</span>
				<ul class="icons">
					<li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i
								class="fas fa-address-card"></i></strong></li>
				</ul>
			</header>
			<!-- Fim Header -->

			<!-- Inicio Cadastro -->
			<section id="banner">
				<div class="content">
					<form method="post">
						{% csrf_token %}
						<div style="margin-bottom: 1rem">
							<label for="id_nome_cargo">Cargo</label>
							<input type="text" name="nome_cargo" maxlength="32" required id="id_nome_cargo">
						</div>
						<div style="margin-bottom: 1rem">
							<label for="id_descricao_cargo">Descrição</label>
							<input type="text" name="descricao_cargo" maxlength="32" id="id_descricao_cargo">
						</div>
						<button type="submit">Salvar</button>
					</form>
				</div>
			</section>
			<!-- Fim Cadastro -->

		</div>
	</div>

	{% include 'menu.html' %}

</div>

{% endblock content %}

adm/templates/cadastrar/cadastrar_fases.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div id="wrapper">
	<div id="main">
		<div class="inner">

			{% include 'mensagem.html' %}
			
			<!-- Inicio Header -->
			<header id="header">
				<span class="label"><strong>Administração</strong> >> Cadastrar >> Fase</span>
				<ul class="icons"><li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i class="fas fa-address-card"></i></strong></li></ul>
			</header>
			<!-- Fim Header -->

			<!-- Inicio Cadastro -->
			<section id="banner">
				<div class="content">
					<form method="post">
						{% csrf_token %}
						<div style="margin-bottom: 1rem">
							<label for="id_fase">Fase</label>
							<input type="text" name="fase" maxlength="128" required="" id="id_fase">
						</div>
							<div style="margin-bottom: 1rem">
							<label for="id_descricao_fase">Descrição</label>
							<input type="text" name="descricao_fase" id="id_descricao_fase">
						</div>
						<button type="submit">Salvar</button>
					</form>
				</div>
			</section>
			<!-- Fim Cadastro -->

		</div>
	</div>

	{% include 'menu.html' %}

</div>

{% endblock content %}

adm/templates/cadastrar/cadastrar_faseusuario.html
<div class="modal fade" id="confirmCadastroFaseModal" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirmCadastroFaseModal" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" id="formCadastroFase" action="">
                {% csrf_token %} 
                <div class="modal-body d-flex justify-content-center">
                    <p> 
                        <b id="fase_id"></b>
                        <input type="text" name="id_vaga_usuario" id="id_vaga_usuario" style="display: none">
                        <input style="margin-bottom: 1rem; color: #000;" type="text" list="fases" autocomplete="off" name="fase" id="fase" placeholder="Fase">
                        <datalist id="fases">
                            {% for i in fases %}
                                <option value="{{ i.fase }}"/>
                            {% endfor %}
                        </datalist>
                        <textarea style="color: #000;" name="observacao" id="observacao" placeholder="Observações" rows="4" cols="50"></textarea>                       
                    </p>              
                </div>
                <div class="modal-footer d-flex justify-content-center align-self-center text-center">
                    <button type="button" class="mr-2" data-dismiss="modal">Cancelar</button>
                    <button type="submit" name="adicionar_fase" id="confirmarCadastroFaseButton">Salvar</button>
                </div> 
            </form>     
        </div>
    </div>
</div>

adm/templates/cadastrar/cadastrar_requisicao.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div id="wrapper">
	<div id="main">
		<div class="inner">

			{% include 'mensagem.html' %}
			
			<!-- Inicio Header -->
			<header id="header">
				<span class="label"><strong>Administração</strong> >> Cadastrar >> Requisição</span>
				<ul class="icons"><li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i class="fas fa-address-card"></i></strong></li></ul>
			</header>
			<!-- Fim Header -->

			<!-- Inicio Cadastro -->
			<section id="banner">
				<div class="content">
					<form method="post">
						{% csrf_token %}
						<div class="row" style="margin-bottom: 1rem">
							<div class="col-2">
								<label>Código</label>
								{{form.codigo}}
							</div>
							<div class="col-4">
								<label>Contratação</label>
								{{form.tipo_vaga}}
							</div>
							<div class="col-4">
								<label>Nível de Ensino</label>
								{{form.ensino}}
							</div>
						</div>
						<div class="row" style="margin-bottom: 1rem">
							<div class="col-4">
								<label>Regiao</label>
								{{form.filial}}
							</div>
							<div class="col-4">
								<label>Setor</label>
								{{form.setor}}
							</div>
							<div class="col-4">
								<label>Cargo</label>
								{{form.cargo}}
							</div>
						</div>
						<br>
						<div class="row" style="margin-bottom: 1rem">
							<div class="col-4">
								<label>Salario</label>
								{{form.salario}}
							</div>
							<div class="col-4">
								<label>Gestor</label>
								{{form.gestor}}
							</div>
							<div class="col-4">
								<label>Tipo de requisição</label>
								{{form.tipo}}
							</div>
						</div>
						<br>

						<div style="margin-bottom: 1rem">
							<label>Requisitos</label>
							{{form.requisitos}}
						</div>

						<div style="margin-bottom: 1rem">
							<label>Atividades</label>
							{{form.atividades}}
						</div>

						<div style="margin-bottom: 1rem">
							<label>Habilidades</label>
							{{form.habilidades}}
						</div>

						<div style="margin-bottom: 1rem">
							<label>Ferramentas</label>
							{{form.ferramentas}}
						</div>

						<div style="margin-bottom: 1rem">
							<label>Recrutamento</label>
							{{form.recrutamento}}
						</div>

						<div style="margin-bottom: 1rem">
							<label>Informações</label>
							{{form.informacoes}}
						</div>

						<button type="submit">Salvar</button>
					</form>
				</div>
			</section>
			<!-- Fim Cadastro -->

			<style>
				[type="number"] {
					border-radius: 5px;
					height: 2.75em;
					border: solid 1px rgba(210, 215, 217, 0.75);
				}

				[type="date"] {
					background: #fff url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png) 97% 50% no-repeat;
					height: 2.75em;
					border: solid 1px rgba(210, 215, 217, 0.75);
					border-radius: 5px;
				}
			
				[type="date"]::-webkit-inner-spin-button {
					display: none;
				}
			
				[type="date"]::-webkit-calendar-picker-indicator {
					opacity: 0;
				}		
			</style>
		</div>
	</div>

	{% include 'menu.html' %}

</div>

{% endblock content %}

adm/templates/cadastrar/cadastrar_setores.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div id="wrapper">
	<div id="main">
		<div class="inner">

			{% include 'mensagem.html' %}

			<!-- Inicio Header -->
			<header id="header">
				<span class="label"><strong>Administração</strong> >> Cadastrar >> Setor</span>
				<ul class="icons">
					<li style="font-size: 18px; letter-spacing:0.1em"><strong>RECSEL <i
								class="fas fa-address-card"></i></strong></li>
				</ul>
			</header>
			<!-- Fim Header -->

			<!-- Inicio Cadastro -->
			<section id="banner">
				<div class="content">
					<form method="post">
						{% csrf_token %}
						<div style="margin-bottom: 1rem">
							<label for="id_nome_setor">Setor</label>
							<input type="text" name="nome_setor" maxlength="32" required="" id="id_nome_setor">
						</div>
						<div style="margin-bottom: 1rem">
							<label for="id_descricao_setor">Descrição</label>
							<input type="text" name="descricao_setor" maxlength="32" id="id_descricao_setor">
						</div>
						<button type="submit">Salvar</button>
					</form>
				</div>
			</section>
			<!-- Fim Cadastro -->

		</div>
	</div>

	{% include 'menu.html' %}

</div>

{% endblock content %}